### ISSUE TITLE
richiesta prova finale

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/AgostiniDavide#1]
se non sbaglio, non hai ancora fatto la richiesta di prova finale sul Portale della Didattica.
Ricorda che ci sono due fasi: la richiesta di tesi (da fare!) e la richiesta di conclusione (che dovrai fare quando avrai finito il progetto).

**Comment by davide2809** [comment]
Professore mi scuso perchè pensavo di averla già fatta.
Appena mi sono reso conto del problema ho subito rimediato.
Mi scuso per l'inconveniente!

**Comment by davide2809** [comment]
Professore ho completato il progetto, se accetta la richiesta di tesi faccio immediatamente le richiesta di conclusione!

**Comment by fulcorno** [comment]
fatto.
