### ISSUE TITLE
importazione del DB

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/AgostiniDavide#2]
La procedura di importazione del DB è molto macchinosa...
Tra l'altro non capisco se i dati presenti nei file ZIP siano gli stessi dei file CSV, o se occorra importarli entrambi.

Vorrei provare ad importare il file SQL completo (gestendo eventuali problemi di prestazioni), ma il file presente su Dropbox non contiene al suo interno le istruzioni CREATE TABLE, quindi non funziona.

**Comment by davide2809** [comment]
Buongiorno professore,
I file sql e i file csv sono gli stessi (ovvero contengono gli stessi dati) ma al fine di effettuare un'operazione più corretta è necessario prima provare ad importare i file sql delle regioni e poi, in caso di errore, importare i file csv.
Non mi ero reso conto del problema nel file SQL completo, perciò adesso ho effettuato numerosi cambiamenti e dovrebbe funzionare e non impiegare troppo tempo. (In caso contrario mi scriva nuovamente)
Oltre a questo mi sono reso conto ora che dopo il Commit lettere accentate e ü sono state sostituiti (ovviamente) con altri caratteri. Perciò in questo momento effettuerò un Commit per risolvere questo problema e aggiornerò il readme.

**Comment by davide2809** [comment]
Gentile professore,
Volevo chiederle se il progetto è funzionante o se necessita di ulteriori modifiche.
Mi scuso per l'insistenza e le auguro buona giornata.
